require("andry.lazy-setup")
vim.loader.enable()
require("andry.core.options")
require("andry.core.keymaps")
require("andry.core.colorscheme")

require("andry.plugins.comment")
require("andry.plugins.nvim-tree")
require("andry.plugins.lualine")
require("andry.plugins.telescope")
require("andry.plugins.nvim-cmp")
require("andry.plugins.lsp.mason")
require("andry.plugins.autopairs")
require("andry.plugins.lsp.lspsaga")
require("andry.plugins.lsp.lspconfig")
require("andry.plugins.lsp.null-ls")
require("andry.plugins.gitsigns")
require("andry.plugins.faster")
require("andry.plugins.tinyInlineDiagnostic")
require("andry.plugins.easymotion")
require("andry.plugins.colorizer")
require("andry.plugins.truezen")
require("andry.plugins.harpoon")
require("andry.plugins.vim-fugitive")
require("andry.plugins.oil")
require("andry.plugins.illuminate")
require("andry.plugins.twilight")
require("andry.plugins.todo")

require("andry.plugins.misc")
require("andry.plugins.toggleterm")
require("andry.plugins.better-ts-errors")
require("andry.plugins.indent-blankline")

require("andry.plugins.treesitter")
-- require("andry.plugins.autotag")

-- require("andry.plugins.copilot")
-- require("andry.plugins.pounce")
-- require("andry.plugins.hardtime")
-- require("andry.plugins.auto-sessions")
